apiVersion: apps/v1
kind: Deployment
metadata:
  name: hewo
spec:
  selector:
    matchLabels:
      app: hewo
  replicas: 3
  template: 
    metadata:
      labels:
        app: hewo
    spec:
      containers:
      - name: hewo
        image: thoschu/helloworld:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: hewo
spec:
 type: NodePort
 selector:
   app: hewo
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32032
